DB_HOST = 'localhost'
DB_USER = 'postgres'
DB_PASS = ''
DB_NAME = 'Test'
# DB_HOST = 'fyp-psql.postgres.database.azure.com'
# DB_USER = 'tsuihoiming'
# DB_PASS = 'Qw645987321'
# DB_NAME = 'Development'
