DB_HOST = 'localhost'
DB_USER = 'postgres'
DB_PASS = ''
DB_NAME = 'Test'
AZURE_PSQL_DB_HOST = 'fyp-psql.postgres.database.azure.com'
AZURE_PSQL_DB_USER = 'tsuihoiming'
AZURE_PSQL_DB_PASS = 'Qw645987321'
AZURE_PSQL_DB_NAME = 'Development'